sap.ui.define([
	"sap/ui/base/ManagedObject",
    "sap/ui/model/json/JSONModel",
    "sap/ui/Device"
], function(
	ManagedObject,
    JSONModel,
    Device
) {
	"use strict";

	return ManagedObject.extend("Iffco.clap.model.salesModel", {
        // var objects = [
        //     {
        //         "zsettlement_group" : "",
        //         "zaccount_assignment_group" : "",
        //         "zagency_business" : "",
        //         "zdocument_index_active" : "",
        //         "zmanual_invoice_maintenance" : "",
        //         "zrebate" : "",
        //         "zpricing" : "",
        //         "zinvoicing_dates" : "",
        //         "zinvoicing_list_dates" : "",
        //         "zcustomer_group1" : "",
        //         "zcustomer_group2" : "",
        //         "zcustomer_group3" : "",
        //         "zcustomer_group4" : "",
        //         "zcustomer_group5" : "",
        //         "zcustomer_group" : "",
        //         "zinco_term" : "",
        //         "zinco_location1" : "",
        //         "zpayment_terms" : "",
        //         "zcredit_control_area" : "",
        //         "zpayment_gurantee_procedure" : "",
        //         "zcomplete_delivery" : "",
        //         "zmaximum_number_of_part_delive" : "",
        //         "zpartial_delivery_per_item" : "",
        //         "zunlimited_tolerance" : "",
        //         "zunder_delivery_tolerance" : "",
        //         "zover_delivery_tolerance" : "",
        //         "zbill_to_buyer" : "",
        //         "zonly_ship_to" : "",
        //         "zsales_person" : "",
        //         "zagent" : "",
        //         "zprice_group" : "",
        //         "zpricelist" : "",
        //         "zprice_procedured_term" : "",
        //         "zcustomer_statistics_group" : "",
        //         "zsales_district" : "",
        //         "zsales_office" : "",
        //         "zsales_group" : "",
        //         "zcustomer_group" : "",
        //         "zabc_class" : "",
        //         "zcurrency" : "",
        //         "zaccount_at_customer" : "",
        //         "zswitch_off_rounding" : "",
        //         "zorderprobability" : "",
        //         "zauthorization_group" : "",
        //         "zitemproposal" : "",
        //         "zunit_of_measure_group" : "",
        //         "zexchange_rate_type" : "",
        //         "zpp_customer_procedure" : "",
        //         "zdelivery_priority" : "",
        //         "zshipping_conditions" : "",
        //         "zdelivery_plant" : "",
        //         "zorder_combination" : "",
        //         "zrelevant_pod" : "",
        //         "zpod_timeframe" : "",
        //         "zcountry" : "",
        //         "ztaxcategory" : "",
        //         "ztax_classification" : "",
        //         "ztax_category2" : "",
        //         "ztax_classification2" : "",
        //     }
        // ];
	});
});